// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta2

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ConditionInitParameters struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type ConditionObservation struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type ConditionParameters struct {

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	Expression *string `json:"expression" tf:"expression,omitempty"`

	// +kubebuilder:validation:Optional
	Title *string `json:"title" tf:"title,omitempty"`
}

type SchemaIAMMemberInitParameters struct {
	Condition *ConditionInitParameters `json:"condition,omitempty" tf:"condition,omitempty"`

	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/pubsub/v1beta1.Schema
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// Reference to a Schema in pubsub to populate schema.
	// +kubebuilder:validation:Optional
	SchemaRef *v1.Reference `json:"schemaRef,omitempty" tf:"-"`

	// Selector for a Schema in pubsub to populate schema.
	// +kubebuilder:validation:Optional
	SchemaSelector *v1.Selector `json:"schemaSelector,omitempty" tf:"-"`
}

type SchemaIAMMemberObservation struct {
	Condition *ConditionObservation `json:"condition,omitempty" tf:"condition,omitempty"`

	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`
}

type SchemaIAMMemberParameters struct {

	// +kubebuilder:validation:Optional
	Condition *ConditionParameters `json:"condition,omitempty" tf:"condition,omitempty"`

	// +kubebuilder:validation:Optional
	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/pubsub/v1beta1.Schema
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// Reference to a Schema in pubsub to populate schema.
	// +kubebuilder:validation:Optional
	SchemaRef *v1.Reference `json:"schemaRef,omitempty" tf:"-"`

	// Selector for a Schema in pubsub to populate schema.
	// +kubebuilder:validation:Optional
	SchemaSelector *v1.Selector `json:"schemaSelector,omitempty" tf:"-"`
}

// SchemaIAMMemberSpec defines the desired state of SchemaIAMMember
type SchemaIAMMemberSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SchemaIAMMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SchemaIAMMemberInitParameters `json:"initProvider,omitempty"`
}

// SchemaIAMMemberStatus defines the observed state of SchemaIAMMember.
type SchemaIAMMemberStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SchemaIAMMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// SchemaIAMMember is the Schema for the SchemaIAMMembers API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp}
type SchemaIAMMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.member) || (has(self.initProvider) && has(self.initProvider.member))",message="spec.forProvider.member is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.role) || (has(self.initProvider) && has(self.initProvider.role))",message="spec.forProvider.role is a required parameter"
	Spec   SchemaIAMMemberSpec   `json:"spec"`
	Status SchemaIAMMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SchemaIAMMemberList contains a list of SchemaIAMMembers
type SchemaIAMMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SchemaIAMMember `json:"items"`
}

// Repository type metadata.
var (
	SchemaIAMMember_Kind             = "SchemaIAMMember"
	SchemaIAMMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SchemaIAMMember_Kind}.String()
	SchemaIAMMember_KindAPIVersion   = SchemaIAMMember_Kind + "." + CRDGroupVersion.String()
	SchemaIAMMember_GroupVersionKind = CRDGroupVersion.WithKind(SchemaIAMMember_Kind)
)

func init() {
	SchemeBuilder.Register(&SchemaIAMMember{}, &SchemaIAMMemberList{})
}
